### ISSUE TITLE
Not able to access gallery

### ISSUE THREAD

**Issue by guilhermefmbatista** [yazeed44/MultiImagePicker#11]
Hi!
I really liked your component and i´m trying to use it in my application but i´m getting an issue.
I did all the things listed in your github page, but when i try to open the gallery, i´m having the following issue:

Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag.

And i´m calling the picker like you did
new Picker.Builder(getBaseContext(),new MyPickListener())
        .build()
        .startActivity();

Can you help me out?
I´ll appreciate.
Thanks

**Comment by yazeed44** [comment]
Can you send your source code ?

for now try to replace getBaseContext() with this , if you are calling it inside an activity

**Comment by guilhermefmbatista** [comment]
I replaced the getBaseContext() with this and worked great!
Thanks alot for the reply.

**Comment by yazeed44** [comment]
You're welcome , I will also be grateful to you if you gave me your feedback about this library
on : g--56@hotmail.com
