### ISSUE TITLE
DarkActionBar

### ISSUE THREAD

**Issue by makoru** [yazeed44/MultiImagePicker#12]
Hello! Beautiful lib, though I failed to implement it easily into my project.
App crashes when AlbumActivity calls getSupportActionBar.
I suppose that happens because of the theme. I'm using Theme.Appcompat.Light.NoActionBar and Toolbar as a separate layout.

**Comment by yazeed44** [comment]
Could you send the log ?

I was going to implement setting A user-made actionbar for more flexibility

**Comment by yazeed44** [comment]
Should be fixed in 1.1 version since i use toolbar instead of actionbar
