### ISSUE TITLE
Showing images which are not in gallery? 

### ISSUE THREAD

**Issue by taimur97** [yazeed44/MultiImagePicker#19]
In my app I am using your library to select images. When the user select images than the app moves the images to some other place and they are deleted from the gallery but if I again click the button to select more pictures the images are still there at the same place. The images don't appear in the gallery because they have been moved. It seems like the library is not refreshing. So how can I refresh the images in the library?

**Comment by taimur97** [comment]
I don't know but it seems like the images are taking some time to disappear from your library but they are disappeared instantly from phones gallery

**Comment by yazeed44** [comment]
I think i got a good idea about the source of this problem , but i need test to confirm it
Could you give me exactly the steps you did to produce this bug ?

**Comment by taimur97** [comment]
It's simple create a button inside an app and select images when it is clicked. After that when the images are successfully picked get all paths of images move the images one by one to another location and also delete them from the mediastore. Now again click to select more pictures and you will see all the moved pictures still there but if you goto your phone's gallery or to the place where they were stored before they were moved you won't find them. 

BTW Any idea how much it will take for you to fix it and if you need any help let me know

**Comment by yazeed44** [comment]
I tried picking image , then removing it , then trying to pick it up again and i didn't find it

Anyway do you have telegram so we can chat ?

I'm gonna create new branch for fixing this bug

**Comment by taimur97** [comment]
Sorry for my late reply 
Just installed Telegram(Never used it before) Give me your number so we can chat

**Comment by yazeed44** [comment]
telegram.me/yazeed44

**Comment by yazeed44** [comment]
Will be solved on 1.1 version
