### ISSUE TITLE
Add option for camera button

### ISSUE THREAD

**Issue by Arkar-Aung** [yazeed44/MultiImagePicker#32]
Hi, 
It will be better if an option for showing/hiding camera button is available. In my case, I don't want to let user to take photo by camera, just only let them to pick images from gallery.

**Comment by yazeed44** [comment]
At first i thought i will fix camera issues at once , but it seems it will need more time to get fixed https://github.com/commonsguy/cwac-cam2/issues/48

I will add one today as 1.1.2

**Comment by yazeed44** [comment]
Implemented in 1.1.2

Use ```disableCaptureImageFromCamera``` in Builder
