### ISSUE TITLE
Pictures in Picker are not appearing in my app

### ISSUE THREAD

**Issue by banietp** [yazeed44/MultiImagePicker#37]
Hi, this is really weird and I've been spending hours on this. If I launch your sample app, I could see everything is working fine, even if I referenced the imagePicker library non directly, meaning through gradle. However, if I copy pasted your sample app into my own app (pretty much the MainActivity class and wtv it references, it launches the Picker activity fine but I dont see the images, even after I select them. I only see the count.

Any idea as to what I'm missing here or what's different? The sample app is already simple enough. One thing I could guess is because my app also uses Glide, however I'm not sure where things went wrong here.

This is what the MainActivity looks like pasted into my app:
![screenshot_2015-07-24-19-04-21](https://cloud.githubusercontent.com/assets/12056752/8886382/400f4be2-3237-11e5-9328-f735fd7c1778.png)
![screenshot_2015-07-24-19-04-16](https://cloud.githubusercontent.com/assets/12056752/8886380/400e5c1e-3237-11e5-8381-7c4a260aed0b.png)
![screenshot_2015-07-24-19-04-07](https://cloud.githubusercontent.com/assets/12056752/8886381/400e6150-3237-11e5-9e44-29d3355068f6.png)

and of course this is what MainActivity looks like just by itself from your sample app:
![screenshot_2015-07-24-19-05-11](https://cloud.githubusercontent.com/assets/12056752/8886399/7c9ff656-3237-11e5-8c8a-a38a70e25ed5.png)
![screenshot_2015-07-24-19-05-06](https://cloud.githubusercontent.com/assets/12056752/8886397/7c9dee42-3237-11e5-85ca-dabd4d795126.png)
![screenshot_2015-07-24-19-04-56](https://cloud.githubusercontent.com/assets/12056752/8886398/7c9fea8a-3237-11e5-95ed-3c26e38bde37.png)

**Comment by yazeed44** [comment]
Did you set custom settings for glide ?

**Comment by banietp** [comment]
Thanks, you are correct! I completely forgot about that. It's a simple fix, and everything works now.

I have another question regarding using your fragments directly, but I'll make another issue thread
