### ISSUE TITLE
Changing camera icon bug

### ISSUE THREAD

**Issue by paatz04** [yazeed44/MultiImagePicker#67]
Hey,

There is a bug with an icon when you switch from back to front camera. The icon stays as it is when you click it once, but when you close it, the icon changes to an x. So when it's closed it shows an x and when it's open it shows the settings icon.

Nexus 4 with Android 5.1.1

**Comment by yazeed44** [comment]
Seems like a bug with [cwac-cam2](https://github.com/commonsguy/cwac-cam2)

Create an issue on their repo.

**Comment by paatz04** [comment]
Just wanted to help - I don't care at all.
