### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by borjaruiz** [yazeed44/MultiImagePicker#80]
I have problems of memory recieving imageEntry on "onPickedSuccessfully.
Error in (getResizedBitmap(MediaStore...)
Tested in Samsung galaxy s3 android: 4.3 (OOM)
Tested in One plus one android: 5.1 (correct).

@Override
        public void onPickedSuccessfully(final ArrayList<ImageEntry> images)
        {
            try{
                File file = new File(images.get(0).path);
                Bitmap bitmap = getResizedBitmap(MediaStore.Images.Media.getBitmap(getContentResolver(), Uri.fromFile(file)), 800);
}

private Bitmap getResizedBitmap(Bitmap bm, int max_size) {
        Bitmap retorn;
        float aspectRatio;
        int width, height;
        if (bm.getWidth() > bm.getHeight()) {
            aspectRatio = bm.getWidth() /
                    (float) bm.getHeight();
            width = max_size;
            height = Math.round(width / aspectRatio);
        } else {
            aspectRatio = bm.getHeight() /
                    (float) bm.getWidth();
            height = max_size;
            width = Math.round(height / aspectRatio);
        }
        retorn = Bitmap.createScaledBitmap(
                bm, width, height, false);
        bm=null;
        bm.recycle();
        return retorn;
    }

**Comment by yazeed44** [comment]
What's in ```onPickedSuccessfully``` depend on you. Not the library itself.
